//state  唯一数据源  存储组件的数据
//获取state  store.state.count
export default {
    loginResult: "",
    groupAll: "",
    userinfor: "",
    validmenu: "",
    validmenuList: [
        { name: "overview", validmenuid: "1" },
        { name: "saving book", validmenuid: "5" },
        { name: "loss mapping", validmenuid: "2" },
        { name: "data input", validmenuid: "6" },
        { name: "account", validmenuid: "7" },
        { name: "improvement", validmenuid: "3" },
        { name: "project summary", validmenuid: "4" },
    ],
    areaAll: "",
    newArea: "",
    updateAreaRes: "",
    deleteAreaRes: "",
    kpiAll: "",
    addKpiRes: "",
    updateKpiRes: "",
    delKpiRes: "",
    lossAll: "",
    addLossRes: "",
    updateLossRes: "",
    deleteLossRes: "",
    validarea: "",
    userAll: "",
    addResult: "",
    delUserRes: '',
    deleteUserByUserIds: '',
    updatePwdResult: '',
    lineBody: '',
    updatelineBodyRes: '',
    tier2: [],
    improList: [],
    nowline: '',
    itemstatus: '',
    updateItemResult: '',
    lossmappingLinebodyAll: [],
    addObject: '',
    deleteObject: '',
    validLeft: [],
    updateLinebodyWeight: '',
    lossTier3: '',
    addLosstier4time2Res: '',
    kpiTwoLev: '',
    datainputLossTableData: [],
    projectStatus: [],
    addClassinfRes: '',
    addProductRes: '',
    showProductRes: '',
    updateObjectimeAfteraddRes: '',
    showProductNameRes: '',
    deleteProductRes: '',
    updateProductRes: '',
    deleteLoss4dataRes: '',
    productAll: null,
    addProductOneRes: '',
    updateProductByIdRes: '',
    deleteProductByIdRes: '',
    selectProductnameByIdRes: '',
    updateProductnameByIdRes: '',
    showImpItemhistoryRes: null
}